services:
  - type: web
    name: ai-voice-backend
    env: python
    buildCommand: |
      apt-get update
      apt-get install -y \
        libsdl2-dev \
        libsdl2-image-dev \
        libsdl2-mixer-dev \
        libsdl2-ttf-dev \
        portaudio19-dev \
        python3-pyaudio \
        build-essential \
        python3-dev \
        python3-pip \
        python3-setuptools \
        python3-wheel
      python3 -m pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: gunicorn ai_voice_backend:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.7
      - key: GROQ_API_KEY
        sync: false
