services:
  - type: web
    name: ai-voice-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn ai_voice_backend:app
    envVars:
      - key: GROQ_API_KEY
        sync: false
      - key: PYTHON_VERSION
        value: 3.9.0 